name: my_services_generator
description: A new Flutter project.
publish_to: none
version: 1.0.1+2
environment: 
  sdk: '>=2.17.0 <3.0.0'
dependencies: 
  archive: ^3.3.7
  yaml: ^3.1.2
  yaml_modify: ^1.0.1
  yaml_writer: ^1.0.3
